# Generated by Django 3.1.6 on 2022-03-12 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_imagerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=40)),
                ('specialité', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=40)),
                ('age', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('decription_res', models.TextField(blank=True, max_length=5000, null=True)),
                ('categorie_imagerie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prima_app.categorie_imagerie')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prima_app.medecin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
