# Generated by Django 3.1.6 on 2022-03-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prima_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='categorie_imagerie',
            name='nom',
            field=models.CharField(choices=[('Echo abdominal', 'Echo abdominal'), ('Echo Pelvienne', 'Echo Pelvienne'), ('Echo Arbre urinaire', 'Echo Arbre urinaire'), ('Echo Obstétricale', 'Echo Obstétricale'), ('Echo Obstétrical 3D/4D', 'Echo Obstétrical 3D/4D'), ('Echo mamaire(sein)', 'Echo mamaire(sein)'), ('Echo parties moles', 'Echo parties moles'), ('Echo bourses(Testicules)', 'Echo bourses (Testicules)'), ('Echo épaule-Genoux', 'Echo épaule-Génoux'), ('Echo Doppler', 'Echo Doppler'), ('TSA', 'TSA'), ('Membre inférieur', 'Membre inférieur'), ('Membres inférieur', 'Membres inférieur'), ('Bourses', 'Bourses')], max_length=50),
        ),
    ]
